// Fix: Populating the file with mock data for the application.
import { Recipe, WeekPlan, PantryItem, Ingredient } from './types';

const ingredients = {
  BREAD: { name: '2 slices of whole wheat bread', category: 'Bakery' } as Ingredient,
  AVOCADO: { name: '1 avocado', category: 'Produce' } as Ingredient,
  EGGS: { name: '2 large eggs', category: 'Dairy' } as Ingredient,
  RED_PEPPER_FLAKES: { name: '1/4 tsp red pepper flakes', category: 'Spices' } as Ingredient,
  SALT_PEPPER: { name: 'Salt and pepper', category: 'Spices' } as Ingredient,
  CHICKEN_BREAST: { name: '1 grilled chicken breast, sliced', category: 'Protein' } as Ingredient,
  MIXED_GREENS: { name: '4 cups mixed greens', category: 'Produce' } as Ingredient,
  CHERRY_TOMATOES: { name: '1/2 cup cherry tomatoes, halved', category: 'Produce' } as Ingredient,
  CUCUMBER: { name: '1/4 cup cucumber, sliced', category: 'Produce' } as Ingredient,
  VINAIGRETTE: { name: '2 tbsp vinaigrette', category: 'Pantry Staples' } as Ingredient,
  GROUND_BEEF: { name: '1 lb ground beef', category: 'Protein' } as Ingredient,
  ONION: { name: '1 onion, chopped', category: 'Produce' } as Ingredient,
  GARLIC: { name: '2 cloves garlic, minced', category: 'Produce' } as Ingredient,
  CRUSHED_TOMATOES: { name: '1 (28 ounce) can crushed tomatoes', category: 'Pantry Staples' } as Ingredient,
  TOMATO_PASTE: { name: '1 (6 ounce) can tomato paste', category: 'Pantry Staples' } as Ingredient,
  OREGANO: { name: '1 tsp dried oregano', category: 'Spices' } as Ingredient,
  SPAGHETTI: { name: '1 pound spaghetti', category: 'Pantry Staples' } as Ingredient,
  QUINOA: { name: '1 cup cooked quinoa', category: 'Pantry Staples' } as Ingredient,
  BLACK_BEANS: { name: '1/2 cup black beans, rinsed', category: 'Pantry Staples' } as Ingredient,
  CORN: { name: '1/2 cup corn', category: 'Produce' } as Ingredient,
  BELL_PEPPER: { name: '1/2 bell pepper, chopped', category: 'Produce' } as Ingredient,
  SALSA: { name: '1/4 cup salsa', category: 'Pantry Staples' } as Ingredient,
  GREEK_YOGURT: { name: '1 cup Greek yogurt', category: 'Dairy' } as Ingredient,
  MIXED_BERRIES: { name: '1/2 cup mixed berries', category: 'Produce' } as Ingredient,
  GRANOLA: { name: '1/4 cup granola', category: 'Pantry Staples' } as Ingredient,
  HONEY: { name: '1 tbsp honey', category: 'Pantry Staples' } as Ingredient,
  SALMON_FILLET: { name: '1 salmon fillet (6 oz)', category: 'Protein' } as Ingredient,
  ASPARAGUS: { name: '1 bunch asparagus, trimmed', category: 'Produce' } as Ingredient,
  OLIVE_OIL: { name: '1 tbsp olive oil', category: 'Pantry Staples' } as Ingredient,
  LEMON: { name: '1 lemon, sliced', category: 'Produce' } as Ingredient,
};

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 1,
    name: 'Avocado Toast with Egg',
    category: 'vegetarian',
    ingredients: [ingredients.BREAD, ingredients.AVOCADO, ingredients.EGGS, ingredients.RED_PEPPER_FLAKES, ingredients.SALT_PEPPER],
    instructions: ['Toast bread slices.', 'Mash avocado and spread on toast.', 'Cook eggs as desired (fried or poached).', 'Place egg on top of avocado toast and season.'],
    prepTime: '5 min',
    cookTime: '5 min',
    servings: 1,
    imageUrl: 'https://images.unsplash.com/photo-1584042214457-13583c4a2206?q=80&w=2940&auto=format&fit=crop',
    nutrition: { calories: 350, protein: 15, carbs: 30, fat: 20 },
  },
  {
    id: 2,
    name: 'Grilled Chicken Salad',
    category: 'non-veg',
    ingredients: [ingredients.CHICKEN_BREAST, ingredients.MIXED_GREENS, ingredients.CHERRY_TOMATOES, ingredients.CUCUMBER, ingredients.VINAIGRETTE],
    instructions: ['In a large bowl, combine mixed greens, tomatoes, and cucumber.', 'Top with sliced grilled chicken.', 'Drizzle with vinaigrette and toss to combine.'],
    prepTime: '10 min',
    cookTime: '0 min',
    servings: 1,
    imageUrl: 'https://images.unsplash.com/photo-1565599244247-4c33054a8e80?q=80&w=2940&auto=format&fit=crop',
    nutrition: { calories: 400, protein: 40, carbs: 10, fat: 22 },
  },
  {
    id: 3,
    name: 'Spaghetti Bolognese',
    category: 'non-veg',
    ingredients: [ingredients.GROUND_BEEF, ingredients.ONION, ingredients.GARLIC, ingredients.CRUSHED_TOMATOES, ingredients.TOMATO_PASTE, ingredients.OREGANO, ingredients.SPAGHETTI],
    instructions: ['Cook beef, onion, and garlic in a large pot. Drain fat.', 'Stir in tomatoes, tomato paste, and oregano. Simmer for 1 hour.', 'Cook spaghetti according to package directions.', 'Serve sauce over spaghetti.'],
    prepTime: '15 min',
    cookTime: '1 hr 15 min',
    servings: 6,
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e326b20f5452?q=80&w=2940&auto=format&fit=crop',
    nutrition: { calories: 650, protein: 30, carbs: 80, fat: 25 },
  },
  {
    id: 4,
    name: 'Quinoa Bowl with Veggies',
    category: 'vegan',
    ingredients: [ingredients.QUINOA, ingredients.BLACK_BEANS, ingredients.CORN, ingredients.BELL_PEPPER, ingredients.SALSA],
    instructions: ['Combine quinoa, black beans, corn, and bell pepper in a bowl.', 'Top with salsa and mix well.'],
    prepTime: '10 min',
    cookTime: '0 min',
    servings: 1,
    imageUrl: 'https://images.unsplash.com/photo-1512427691650-15fc38914b45?q=80&w=2940&auto=format&fit=crop',
    nutrition: { calories: 380, protein: 15, carbs: 70, fat: 5 },
  },
   {
    id: 5,
    name: 'Greek Yogurt Parfait',
    category: 'vegetarian',
    ingredients: [ingredients.GREEK_YOGURT, ingredients.MIXED_BERRIES, ingredients.GRANOLA, ingredients.HONEY],
    instructions: ['Layer Greek yogurt, berries, and granola in a glass.', 'Drizzle with honey before serving.'],
    prepTime: '5 min',
    cookTime: '0 min',
    servings: 1,
    imageUrl: 'https://images.unsplash.com/photo-1565032475039-026410423e80?q=80&w=2787&auto=format&fit=crop',
    nutrition: { calories: 300, protein: 20, carbs: 40, fat: 8 },
  },
  {
    id: 6,
    name: 'Salmon with Asparagus',
    category: 'non-veg',
    ingredients: [ingredients.SALMON_FILLET, ingredients.ASPARAGUS, ingredients.OLIVE_OIL, ingredients.LEMON, ingredients.SALT_PEPPER],
    instructions: ['Preheat oven to 400°F (200°C).', 'Toss asparagus with olive oil, salt, and pepper on a baking sheet.', 'Place salmon on top, season, and top with lemon slices.', 'Bake for 12-15 minutes.'],
    prepTime: '5 min',
    cookTime: '15 min',
    servings: 1,
    imageUrl: 'https://images.unsplash.com/photo-1623428187969-5da2d2f73e36?q=80&w=2864&auto=format&fit=crop',
    nutrition: { calories: 450, protein: 45, carbs: 10, fat: 28 },
  }
];

export const EMPTY_WEEK_PLAN: WeekPlan = [
  { day: 'Monday', breakfast: { recipe: null }, lunch: { recipe: null }, dinner: { recipe: null } },
  { day: 'Tuesday', breakfast: { recipe: null }, lunch: { recipe: null }, dinner: { recipe: null } },
  { day: 'Wednesday', breakfast: { recipe: null }, lunch: { recipe: null }, dinner: { recipe: null } },
  { day: 'Thursday', breakfast: { recipe: null }, lunch: { recipe: null }, dinner: { recipe: null } },
  { day: 'Friday', breakfast: { recipe: null }, lunch: { recipe: null }, dinner: { recipe: null } },
  { day: 'Saturday', breakfast: { recipe: null }, lunch: { recipe: null }, dinner: { recipe: null } },
  { day: 'Sunday', breakfast: { recipe: null }, lunch: { recipe: null }, dinner: { recipe: null } },
];


export const MOCK_PANTRY_ITEMS: PantryItem[] = [
    { id: '1', name: 'Avocado' },
    { id: '2', name: 'Bread' },
    { id: '3', name: 'Quinoa' },
    { id: '4', name: 'Eggs' },
    { id: '5', name: 'Spaghetti' },
    { id: '6', name: 'Black Beans' },
    { id: '7', name: 'Onion' },
];