// Fix: Populating the file with mock data for the application.
import { Recipe, WeekPlan, PantryItem, Ingredient, IngredientCategory } from './types';

export const PRESET_PANTRY_ITEMS: Record<IngredientCategory, Ingredient[]> = {
  'Produce': [
    { name: 'Onion', category: 'Produce', cuisines: ['Any'] },
    { name: 'Garlic', category: 'Produce', cuisines: ['Any'] },
    { name: 'Tomatoes', category: 'Produce', cuisines: ['Any'] },
    { name: 'Potatoes', category: 'Produce', cuisines: ['Any'] },
    { name: 'Carrots', category: 'Produce', cuisines: ['Any'] },
    { name: 'Bell Peppers', category: 'Produce', cuisines: ['American', 'Mexican'] },
    { name: 'Broccoli', category: 'Produce', cuisines: ['American', 'Chinese'] },
    { name: 'Spinach', category: 'Produce', cuisines: ['Any'] },
    { name: 'Lettuce', category: 'Produce', cuisines: ['American'] },
    { name: 'Avocado', category: 'Produce', cuisines: ['Mexican', 'American'] },
    { name: 'Lemon', category: 'Produce', cuisines: ['Any'] },
    { name: 'Lime', category: 'Produce', cuisines: ['Mexican', 'Indian'] },
    { name: 'Ginger', category: 'Produce', cuisines: ['Indian', 'Chinese'] },
    { name: 'Cilantro', category: 'Produce', cuisines: ['Indian', 'Mexican'] },
    { name: 'Basil', category: 'Produce', cuisines: ['Italian'] },
  ],
  'Protein': [
    { name: 'Chicken Breast', category: 'Protein', cuisines: ['Any'] },
    { name: 'Ground Beef', category: 'Protein', cuisines: ['American', 'Mexican', 'Italian'] },
    { name: 'Salmon', category: 'Protein', cuisines: ['American'] },
    { name: 'Shrimp', category: 'Protein', cuisines: ['Chinese', 'American'] },
    { name: 'Tofu', category: 'Protein', cuisines: ['Chinese', 'vegan'] },
    { name: 'Eggs', category: 'Protein', cuisines: ['Any'] },
    { name: 'Canned Tuna', category: 'Protein', cuisines: ['American'] },
    { name: 'Bacon', category: 'Protein', cuisines: ['American'] },
    { name: 'Lamb', category: 'Protein', cuisines: ['Indian'] },
    { name: 'White Fish Fillet', category: 'Protein', cuisines: ['Indian'] },
  ],
   'Dairy': [
    { name: 'Milk', category: 'Dairy', cuisines: ['Any'] },
    { name: 'Butter', category: 'Dairy', cuisines: ['Any'] },
    { name: 'Cheddar Cheese', category: 'Dairy', cuisines: ['American', 'Mexican'] },
    { name: 'Mozzarella Cheese', category: 'Dairy', cuisines: ['Italian'] },
    { name: 'Parmesan Cheese', category: 'Dairy', cuisines: ['Italian'] },
    { name: 'Yogurt', category: 'Dairy', cuisines: ['Any'] },
    { name: 'Sour Cream', category: 'Dairy', cuisines: ['Mexican', 'American'] },
    { name: 'Heavy Cream', category: 'Dairy', cuisines: ['Italian', 'French'] },
  ],
  'Pantry Staples': [
    { name: 'Olive Oil', category: 'Pantry Staples', cuisines: ['Any'] },
    { name: 'Vegetable Oil', category: 'Pantry Staples', cuisines: ['Any'] },
    { name: 'All-Purpose Flour', category: 'Pantry Staples', cuisines: ['Any'] },
    { name: 'Granulated Sugar', category: 'Pantry Staples', cuisines: ['Any'] },
    { name: 'Brown Sugar', category: 'Pantry Staples', cuisines: ['American'] },
    { name: 'Honey', category: 'Pantry Staples', cuisines: ['Any'] },
    { name: 'Rice', category: 'Pantry Staples', cuisines: ['Any'] },
    { name: 'Pasta', category: 'Pantry Staples', cuisines: ['Italian'] },
    { name: 'Breadcrumbs', category: 'Pantry Staples', cuisines: ['Italian', 'American'] },
    { name: 'Soy Sauce', category: 'Pantry Staples', cuisines: ['Chinese'] },
    { name: 'Vinegar', category: 'Pantry Staples', cuisines: ['Any'] },
    { name: 'Canned Tomatoes', category: 'Pantry Staples', cuisines: ['Italian', 'Mexican'] },
    { name: 'Canned Beans', category: 'Pantry Staples', cuisines: ['Mexican', 'American'] },
    { name: 'Lentils', category: 'Pantry Staples', cuisines: ['Indian'] },
    { name: 'Semolina', category: 'Pantry Staples', cuisines: ['Indian'] },
    { name: 'Coconut Milk', category: 'Pantry Staples', cuisines: ['Indian'] },
    { name: 'Tamarind Paste', category: 'Pantry Staples', cuisines: ['Indian'] },
    { name: 'Idli Rice', category: 'Pantry Staples', cuisines: ['Indian'] },
    { name: 'Eno (Fruit Salt)', category: 'Pantry Staples', cuisines: ['Indian'] },
  ],
  'Spices': [
    { name: 'Salt', category: 'Spices', cuisines: ['Any'] },
    { name: 'Black Pepper', category: 'Spices', cuisines: ['Any'] },
    { name: 'Garlic Powder', category: 'Spices', cuisines: ['Any'] },
    { name: 'Onion Powder', category: 'Spices', cuisines: ['Any'] },
    { name: 'Paprika', category: 'Spices', cuisines: ['American', 'Mexican'] },
    { name: 'Chili Powder', category: 'Spices', cuisines: ['Mexican', 'Indian'] },
    { name: 'Cumin', category: 'Spices', cuisines: ['Mexican', 'Indian'] },
    { name: 'Oregano', category: 'Spices', cuisines: ['Italian', 'Mexican'] },
    { name: 'Thyme', category: 'Spices', cuisines: ['French', 'American'] },
    { name: 'Rosemary', category: 'Spices', cuisines: ['French', 'Italian'] },
    { name: 'Turmeric', category: 'Spices', cuisines: ['Indian'] },
    { name: 'Coriander', category: 'Spices', cuisines: ['Indian'] },
    { name: 'Garam Masala', category: 'Spices', cuisines: ['Indian'] },
    { name: 'Kashmiri Red Chili Powder', category: 'Spices', cuisines: ['Indian'] },
    { name: 'Fennel Powder', category: 'Spices', cuisines: ['Indian'] },
    { name: 'Ginger Powder', category: 'Spices', cuisines: ['Indian'] },
  ],
  'Bakery': [
    { name: 'Bread', category: 'Bakery', cuisines: ['Any'] },
    { name: 'Tortillas', category: 'Bakery', cuisines: ['Mexican'] },
    { name: 'Buns', category: 'Bakery', cuisines: ['American'] },
  ]
};


const ingredients = {
  BREAD: { name: '2 slices of whole wheat bread', category: 'Bakery' } as Ingredient,
  AVOCADO: { name: '1 avocado', category: 'Produce' } as Ingredient,
  EGGS: { name: '2 large eggs', category: 'Dairy' } as Ingredient,
  RED_PEPPER_FLAKES: { name: '1/4 tsp red pepper flakes', category: 'Spices' } as Ingredient,
  SALT_PEPPER: { name: 'Salt and pepper', category: 'Spices' } as Ingredient,
  CHICKEN_BREAST: { name: '1 grilled chicken breast, sliced', category: 'Protein' } as Ingredient,
  MIXED_GREENS: { name: '4 cups mixed greens', category: 'Produce' } as Ingredient,
  CHERRY_TOMATOES: { name: '1/2 cup cherry tomatoes, halved', category: 'Produce' } as Ingredient,
  CUCUMBER: { name: '1/4 cup cucumber, sliced', category: 'Produce' } as Ingredient,
  VINAIGRETTE: { name: '2 tbsp vinaigrette', category: 'Pantry Staples' } as Ingredient,
  GROUND_BEEF: { name: '1 lb ground beef', category: 'Protein' } as Ingredient,
  ONION: { name: '1 onion, chopped', category: 'Produce' } as Ingredient,
  GARLIC: { name: '2 cloves garlic, minced', category: 'Produce' } as Ingredient,
  CRUSHED_TOMATOES: { name: '1 (28 ounce) can crushed tomatoes', category: 'Pantry Staples' } as Ingredient,
  TOMATO_PASTE: { name: '1 (6 ounce) can tomato paste', category: 'Pantry Staples' } as Ingredient,
  OREGANO: { name: '1 tsp dried oregano', category: 'Spices' } as Ingredient,
  SPAGHETTI: { name: '1 pound spaghetti', category: 'Pantry Staples' } as Ingredient,
  QUINOA: { name: '1 cup cooked quinoa', category: 'Pantry Staples' } as Ingredient,
  BLACK_BEANS: { name: '1/2 cup black beans, rinsed', category: 'Pantry Staples' } as Ingredient,
  CORN: { name: '1/2 cup corn', category: 'Produce' } as Ingredient,
  BELL_PEPPER: { name: '1/2 bell pepper, chopped', category: 'Produce' } as Ingredient,
  SALSA: { name: '1/4 cup salsa', category: 'Pantry Staples' } as Ingredient,
  GREEK_YOGURT: { name: '1 cup Greek yogurt', category: 'Dairy' } as Ingredient,
  MIXED_BERRIES: { name: '1/2 cup mixed berries', category: 'Produce' } as Ingredient,
  GRANOLA: { name: '1/4 cup granola', category: 'Pantry Staples' } as Ingredient,
  HONEY: { name: '1 tbsp honey', category: 'Pantry Staples' } as Ingredient,
  SALMON_FILLET: { name: '1 salmon fillet (6 oz)', category: 'Protein' } as Ingredient,
  ASPARAGUS: { name: '1 bunch asparagus, trimmed', category: 'Produce' } as Ingredient,
  OLIVE_OIL: { name: '1 tbsp olive oil', category: 'Pantry Staples' } as Ingredient,
  LEMON: { name: '1 lemon, sliced', category: 'Produce' } as Ingredient,
  // Indian Ingredients
  POHA: { name: '1.5 cups thick poha (flattened rice)', category: 'Pantry Staples' } as Ingredient,
  TURMERIC: { name: '1/4 tsp turmeric powder', category: 'Spices' } as Ingredient,
  MUSTARD_SEEDS: { name: '1 tsp mustard seeds', category: 'Spices' } as Ingredient,
  CURRY_LEAVES: { name: '8-10 curry leaves', category: 'Produce' } as Ingredient,
  GREEN_CHILI: { name: '1-2 green chilies, chopped', category: 'Produce' } as Ingredient,
  CORIANDER_LEAVES: { name: '2 tbsp chopped coriander leaves', category: 'Produce' } as Ingredient,
  CHICKPEAS: { name: '1 cup dried chickpeas, soaked overnight', category: 'Pantry Staples' } as Ingredient,
  ALL_PURPOSE_FLOUR: { name: '2 cups all-purpose flour', category: 'Pantry Staples' } as Ingredient,
  YOGURT: { name: '1/4 cup yogurt', category: 'Dairy' } as Ingredient,
  PANEER: { name: '250g paneer, cubed', category: 'Dairy' } as Ingredient,
  GINGER_GARLIC_PASTE: { name: '1 tbsp ginger-garlic paste', category: 'Produce' } as Ingredient,
  TOMATO_PUREE: { name: '1 cup tomato puree', category: 'Pantry Staples' } as Ingredient,
  TOMATO: { name: '1 medium tomato, chopped', category: 'Produce' } as Ingredient,
  CASHEWS: { name: '10-12 cashews', category: 'Pantry Staples' } as Ingredient,
  GARAM_MASALA: { name: '1 tsp garam masala', category: 'Spices' } as Ingredient,
  CREAM: { name: '1/4 cup heavy cream', category: 'Dairy' } as Ingredient,
  CHICKEN: { name: '500g chicken, bone-in', category: 'Protein' } as Ingredient,
  BASMATI_RICE: { name: '2 cups basmati rice, soaked', category: 'Pantry Staples' } as Ingredient,
  BIRYANI_MASALA: { name: '2 tbsp biryani masala', category: 'Spices' } as Ingredient,
  MINT_LEAVES: { name: '1/4 cup mint leaves', category: 'Produce' } as Ingredient,
  DOSA_RICE: { name: '1.5 cups dosa rice', category: 'Pantry Staples' } as Ingredient,
  URAD_DAL: { name: '1/2 cup urad dal', category: 'Pantry Staples' } as Ingredient,
  POTATOES: { name: '2 medium potatoes, boiled and mashed', category: 'Produce' } as Ingredient,
  SAMBAR_POWDER: { name: '2 tsp sambar powder', category: 'Spices' } as Ingredient,
  TOOR_DAL: { name: '1 cup toor dal (split pigeon peas)', category: 'Pantry Staples' } as Ingredient,
  CUMIN_SEEDS: { name: '1 tsp cumin seeds', category: 'Spices' } as Ingredient,
  DRIED_RED_CHILI: { name: '2 dried red chilies', category: 'Spices' } as Ingredient,
  // New South Indian & Snack Ingredients
  TAMARIND_PULP: { name: '1 tbsp tamarind pulp', category: 'Pantry Staples' } as Ingredient,
  MIXED_VEGETABLES: { name: '1 cup mixed vegetables (carrots, beans, drumstick)', category: 'Produce' } as Ingredient,
  GRATED_COCONUT: { name: '1/2 cup grated coconut', category: 'Produce' } as Ingredient,
  RASAM_POWDER: { name: '2 tsp rasam powder', category: 'Spices' } as Ingredient,
  BLACK_PEPPER: { name: '1 tsp black pepper', category: 'Spices' } as Ingredient,
  GREEN_PEAS: { name: '1/2 cup green peas', category: 'Produce' } as Ingredient,
  CORIANDER_POWDER: { name: '1 tsp coriander powder', category: 'Spices' } as Ingredient,
  GRAM_FLOUR: { name: '1 cup gram flour (besan)', category: 'Pantry Staples' } as Ingredient,
  AJWAIN: { name: '1/2 tsp ajwain (carom seeds)', category: 'Spices' } as Ingredient,
  PAV_BUNS: { name: '4 pav (bread buns)', category: 'Bakery' } as Ingredient,
  GREEN_CHUTNEY: { name: '2 tbsp green chutney', category: 'Pantry Staples' } as Ingredient,
  
  // NEW INGREDIENTS FOR EXPANDED CUISINES
  TORTILLAS: { name: '8 corn tortillas', category: 'Bakery' } as Ingredient,
  TACO_SEASONING: { name: '1 tbsp taco seasoning', category: 'Spices' } as Ingredient,
  LETTUCE: { name: '1 cup shredded lettuce', category: 'Produce' } as Ingredient,
  CHEDDAR_CHEESE: { name: '1 cup shredded cheddar cheese', category: 'Dairy' } as Ingredient,
  SOUR_CREAM: { name: '1/4 cup sour cream', category: 'Dairy' } as Ingredient,
  ENCHILADA_SAUCE: { name: '1 can (15 oz) enchilada sauce', category: 'Pantry Staples' } as Ingredient,
  SOY_SAUCE: { name: '1/4 cup soy sauce', category: 'Pantry Staples' } as Ingredient,
  RICE_VINEGAR: { name: '2 tbsp rice vinegar', category: 'Pantry Staples' } as Ingredient,
  PEANUTS: { name: '1/2 cup roasted peanuts', category: 'Pantry Staples' } as Ingredient,
  SCALLIONS: { name: '2 scallions, chopped', category: 'Produce' } as Ingredient,
  GINGER: { name: '1 tbsp minced ginger', category: 'Produce' } as Ingredient,
  TOFU: { name: '1 block firm tofu', category: 'Protein' } as Ingredient,
  SICHUAN_PEPPERCORNS: { name: '1 tsp Sichuan peppercorns', category: 'Spices' } as Ingredient,
  CHILI_BEAN_PASTE: { name: '2 tbsp chili bean paste', category: 'Pantry Staples' } as Ingredient,
  VEGETABLE_BROTH: { name: '4 cups vegetable broth', category: 'Pantry Staples' } as Ingredient,
  BAGUETTE: { name: '4 slices baguette', category: 'Bakery' } as Ingredient,
  GRUYERE_CHEESE: { name: '1 cup shredded Gruyère', category: 'Dairy' } as Ingredient,
  BUTTER: { name: '2 tbsp butter', category: 'Dairy' } as Ingredient,
  THYME: { name: '4 sprigs fresh thyme', category: 'Spices' } as Ingredient,
  EGGPLANT: { name: '1 eggplant, cubed', category: 'Produce' } as Ingredient,
  ZUCCHINI: { name: '1 zucchini, cubed', category: 'Produce' } as Ingredient,
  MUSHROOMS: { name: '8 oz mushrooms, sliced', category: 'Produce' } as Ingredient,
  HERBS_DE_PROVENCE: { name: '1 tsp herbs de provence', category: 'Spices' } as Ingredient,
  // NEW REGIONAL INDIAN INGREDIENTS
  ENO: { name: '1 tsp Eno (fruit salt)', category: 'Pantry Staples' } as Ingredient,
  SEMOLINA: { name: '2 tbsp semolina (sooji)', category: 'Pantry Staples' } as Ingredient,
  LAMB: { name: '500g lamb, cut into pieces', category: 'Protein' } as Ingredient,
  KASHMIRI_CHILI_POWDER: { name: '2 tsp Kashmiri red chili powder', category: 'Spices' } as Ingredient,
  FENNEL_POWDER: { name: '1 tsp fennel powder', category: 'Spices' } as Ingredient,
  GINGER_POWDER: { name: '1/2 tsp ginger powder', category: 'Spices' } as Ingredient,
  WHITE_FISH: { name: '400g white fish fillets', category: 'Protein' } as Ingredient,
  COCONUT_MILK: { name: '1 cup coconut milk', category: 'Pantry Staples' } as Ingredient,
  IDLI_RICE: { name: '2 cups idli rice', category: 'Pantry Staples' } as Ingredient,
  TAMARIND_PASTE: { name: '2 tsp tamarind paste', category: 'Pantry Staples' } as Ingredient,
};

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 1,
    name: 'Avocado Toast with Egg',
    category: 'vegetarian',
    cuisine: 'American',
    ingredients: [ingredients.BREAD, ingredients.AVOCADO, ingredients.EGGS, ingredients.RED_PEPPER_FLAKES, ingredients.SALT_PEPPER],
    instructions: ['Toast bread slices.', 'Mash avocado and spread on toast.', 'Cook eggs as desired (fried or poached).', 'Place egg on top of avocado toast and season.'],
    prepTime: '5 min',
    cookTime: '5 min',
    servings: 1,
    imageUrl: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?q=80&w=1910&auto=format&fit=crop',
    nutrition: { calories: 350, protein: 15, carbs: 30, fat: 20 },
  },
  {
    id: 2,
    name: 'Grilled Chicken Salad',
    category: 'non-veg',
    cuisine: 'American',
    ingredients: [ingredients.CHICKEN_BREAST, ingredients.MIXED_GREENS, ingredients.CHERRY_TOMATOES, ingredients.CUCUMBER, ingredients.VINAIGRETTE],
    instructions: ['In a large bowl, combine mixed greens, tomatoes, and cucumber.', 'Top with sliced grilled chicken.', 'Drizzle with vinaigrette and toss to combine.'],
    prepTime: '10 min',
    cookTime: '0 min',
    servings: 1,
    imageUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?q=80&w=1974&auto=format&fit=crop',
    nutrition: { calories: 400, protein: 40, carbs: 10, fat: 22 },
  },
  {
    id: 3,
    name: 'Spaghetti Bolognese',
    category: 'non-veg',
    cuisine: 'Italian',
    ingredients: [ingredients.GROUND_BEEF, ingredients.ONION, ingredients.GARLIC, ingredients.CRUSHED_TOMATOES, ingredients.TOMATO_PASTE, ingredients.OREGANO, ingredients.SPAGHETTI],
    instructions: ['Cook beef, onion, and garlic in a large pot. Drain fat.', 'Stir in tomatoes, tomato paste, and oregano. Simmer for 1 hour.', 'Cook spaghetti according to package directions.', 'Serve sauce over spaghetti.'],
    prepTime: '15 min',
    cookTime: '1 hr 15 min',
    servings: 6,
    imageUrl: 'https://images.unsplash.com/photo-1589227365533-5f6e6ab5ef75?q=80&w=1974&auto=format&fit=crop',
    nutrition: { calories: 650, protein: 30, carbs: 80, fat: 25 },
  },
  {
    id: 4,
    name: 'Quinoa Bowl with Veggies',
    category: 'vegan',
    cuisine: 'American',
    ingredients: [ingredients.QUINOA, ingredients.BLACK_BEANS, ingredients.CORN, ingredients.BELL_PEPPER, ingredients.SALSA],
    instructions: ['Combine quinoa, black beans, corn, and bell pepper in a bowl.', 'Top with salsa and mix well.'],
    prepTime: '10 min',
    cookTime: '0 min',
    servings: 1,
    imageUrl: 'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?q=80&w=1964&auto=format&fit=crop',
    nutrition: { calories: 380, protein: 15, carbs: 70, fat: 5 },
  },
   {
    id: 5,
    name: 'Greek Yogurt Parfait',
    category: 'vegetarian',
    cuisine: 'American',
    ingredients: [ingredients.GREEK_YOGURT, ingredients.MIXED_BERRIES, ingredients.GRANOLA, ingredients.HONEY],
    instructions: ['Layer Greek yogurt, berries, and granola in a glass.', 'Drizzle with honey before serving.'],
    prepTime: '5 min',
    cookTime: '0 min',
    servings: 1,
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17025?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 300, protein: 20, carbs: 40, fat: 8 },
  },
  {
    id: 6,
    name: 'Salmon with Asparagus',
    category: 'non-veg',
    cuisine: 'American',
    ingredients: [ingredients.SALMON_FILLET, ingredients.ASPARAGUS, ingredients.OLIVE_OIL, ingredients.LEMON, ingredients.SALT_PEPPER],
    instructions: ['Preheat oven to 400°F (200°C).', 'Toss asparagus with olive oil, salt, and pepper on a baking sheet.', 'Place salmon on top, season, and top with lemon slices.', 'Bake for 12-15 minutes.'],
    prepTime: '5 min',
    cookTime: '15 min',
    servings: 1,
    imageUrl: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 450, protein: 45, carbs: 10, fat: 28 },
  },
  // --- Indian Recipes Start Here ---
  {
    id: 7,
    name: 'Poha',
    category: 'vegetarian',
    cuisine: 'Indian',
    ingredients: [ingredients.POHA, ingredients.ONION, ingredients.OLIVE_OIL, ingredients.MUSTARD_SEEDS, ingredients.CURRY_LEAVES, ingredients.TURMERIC, ingredients.GREEN_CHILI, ingredients.LEMON, ingredients.CORIANDER_LEAVES],
    instructions: ['Rinse poha in a strainer and let it soften.', 'Heat oil, add mustard seeds, curry leaves, and green chili.', 'Sauté chopped onions until translucent.', 'Add turmeric, then the softened poha and salt. Mix well.', 'Garnish with lemon juice and coriander.'],
    prepTime: '10 min',
    cookTime: '10 min',
    servings: 2,
    imageUrl: 'https://images.unsplash.com/photo-1609503222839-8197c36a053c?q=80&w=2071&auto=format&fit=crop',
    nutrition: { calories: 250, protein: 5, carbs: 50, fat: 4 },
  },
  {
    id: 8,
    name: 'Chole Bhature',
    category: 'vegetarian',
    cuisine: 'Indian',
    ingredients: [ingredients.CHICKPEAS, ingredients.ONION, ingredients.TOMATO_PUREE, ingredients.GINGER_GARLIC_PASTE, ingredients.GARAM_MASALA, ingredients.ALL_PURPOSE_FLOUR, ingredients.YOGURT, ingredients.OLIVE_OIL],
    instructions: ['For Chole: Pressure cook soaked chickpeas. Sauté onions, ginger-garlic paste, and tomato puree. Add spices and cooked chickpeas. Simmer.', 'For Bhature: Make a dough with flour, yogurt, and a little oil. Let it rest. Roll out and deep fry until puffed.'],
    prepTime: '20 min',
    cookTime: '45 min',
    servings: 4,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1663852297241-b7781b41d2a4?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 550, protein: 15, carbs: 75, fat: 20 },
  },
  {
    id: 9,
    name: 'Paneer Butter Masala',
    category: 'vegetarian',
    cuisine: 'Indian',
    // Fix: Added 'as Ingredient' type assertion to fix type errors.
    ingredients: [ingredients.PANEER, ingredients.TOMATO_PUREE, ingredients.ONION, ingredients.CASHEWS, ingredients.GINGER_GARLIC_PASTE, ingredients.GARAM_MASALA, ingredients.CREAM, { name: '1 tbsp butter', category: 'Dairy' } as Ingredient],
    instructions: ['Sauté paneer cubes lightly and set aside.', 'Make a gravy by blending sautéed onions, tomatoes, cashews, and ginger-garlic paste.', 'Cook the gravy with butter and spices.', 'Add paneer and cream. Simmer for a few minutes.'],
    prepTime: '15 min',
    cookTime: '25 min',
    servings: 3,
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 450, protein: 20, carbs: 15, fat: 35 },
  },
  {
    id: 10,
    name: 'Chicken Biryani',
    category: 'non-veg',
    cuisine: 'Indian',
    // Fix: Added 'as Ingredient' type assertion to fix type errors.
    ingredients: [ingredients.CHICKEN, ingredients.BASMATI_RICE, ingredients.YOGURT, ingredients.ONION, ingredients.GINGER_GARLIC_PASTE, ingredients.BIRYANI_MASALA, ingredients.MINT_LEAVES, { name: 'A pinch of saffron', category: 'Spices' } as Ingredient],
    instructions: ['Marinate chicken with yogurt and spices.', 'Fry onions until golden brown.', 'Par-cook the soaked basmati rice.', 'Layer the rice and chicken in a heavy-bottomed pot.', 'Top with fried onions, mint, and saffron milk. Cook on low heat (dum).'],
    prepTime: '30 min',
    cookTime: '1 hr',
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8da7?q=80&w=1974&auto=format&fit=crop',
    nutrition: { calories: 600, protein: 35, carbs: 60, fat: 25 },
  },
  {
    id: 11,
    name: 'Masala Dosa',
    category: 'vegan',
    cuisine: 'Indian',
    ingredients: [ingredients.DOSA_RICE, ingredients.URAD_DAL, ingredients.POTATOES, ingredients.ONION, ingredients.TURMERIC, ingredients.MUSTARD_SEEDS, ingredients.GREEN_CHILI, ingredients.OLIVE_OIL],
    instructions: ['Soak rice and dal, then grind to a batter and ferment overnight.', 'For masala: Sauté mustard seeds, onions, and chilies. Add turmeric and mashed potatoes.', 'Spread the batter thinly on a hot pan to make a dosa. Add filling and fold.'],
    prepTime: '12 hr (includes fermentation)',
    cookTime: '20 min',
    servings: 5,
    imageUrl: 'https://images.unsplash.com/photo-1643216343038-92f784bf1d43?q=80&w=1974&auto=format&fit=crop',
    nutrition: { calories: 300, protein: 8, carbs: 55, fat: 5 },
  },
  {
    id: 12,
    name: 'Dal Tadka',
    category: 'vegan',
    cuisine: 'Indian',
    ingredients: [ingredients.TOOR_DAL, ingredients.ONION, ingredients.TOMATO, ingredients.GINGER_GARLIC_PASTE, ingredients.TURMERIC, ingredients.CUMIN_SEEDS, ingredients.DRIED_RED_CHILI, ingredients.CORIANDER_LEAVES, ingredients.OLIVE_OIL],
    instructions: ['Pressure cook the toor dal with turmeric and salt.', 'For tadka (tempering): Heat oil/ghee, add cumin seeds, dried red chili, and asafoetida.', 'Sauté onions, ginger-garlic paste, and tomatoes.', 'Pour the tadka over the cooked dal. Garnish with coriander.'],
    prepTime: '10 min',
    cookTime: '20 min',
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a0586276d8?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 280, protein: 15, carbs: 40, fat: 6 },
  },
  // --- New South Indian & Snack Recipes ---
  {
    id: 13,
    name: 'Sambar',
    category: 'vegetarian',
    cuisine: 'Indian',
    ingredients: [ingredients.TOOR_DAL, ingredients.TAMARIND_PULP, ingredients.SAMBAR_POWDER, ingredients.MIXED_VEGETABLES, ingredients.MUSTARD_SEEDS, ingredients.CURRY_LEAVES],
    instructions: ['Pressure cook toor dal until soft.', 'Cook vegetables in water with sambar powder and salt.', 'Add tamarind pulp and cooked dal to the vegetables and bring to a boil.', 'Prepare tempering with mustard seeds and curry leaves in oil and add to the sambar.'],
    prepTime: '15 min',
    cookTime: '30 min',
    servings: 4,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1695289949132-888915523a85?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 220, protein: 12, carbs: 35, fat: 4 },
  },
  {
    id: 14,
    name: 'Avial',
    category: 'vegetarian',
    cuisine: 'Indian',
    // Fix: Added 'as Ingredient' type assertion to fix type errors.
    ingredients: [ingredients.MIXED_VEGETABLES, ingredients.GRATED_COCONUT, ingredients.YOGURT, ingredients.GREEN_CHILI, ingredients.CURRY_LEAVES, { name: '1 tsp coconut oil', category: 'Pantry Staples' } as Ingredient],
    instructions: ['Cook mixed vegetables until tender.', 'Grind coconut and green chilies to a fine paste.', 'Add the coconut paste to the cooked vegetables and cook for a few minutes.', 'Whisk yogurt and add it to the curry. Do not boil after adding yogurt.', 'Top with curry leaves and coconut oil.'],
    prepTime: '20 min',
    cookTime: '25 min',
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1644284240952-32a8a1b621a2?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 180, protein: 5, carbs: 15, fat: 12 },
  },
  {
    id: 15,
    name: 'Rasam',
    category: 'vegan',
    cuisine: 'Indian',
    ingredients: [ingredients.TAMARIND_PULP, ingredients.TOMATO, ingredients.RASAM_POWDER, ingredients.BLACK_PEPPER, ingredients.MUSTARD_SEEDS, ingredients.GARLIC],
    instructions: ['Dilute tamarind pulp in water. Add chopped tomatoes, rasam powder, and salt. Boil.', 'Crush garlic and black pepper.', 'Prepare tempering with mustard seeds in oil, add crushed garlic and pepper.', 'Add tempering to the boiling rasam. Garnish with coriander.'],
    prepTime: '5 min',
    cookTime: '15 min',
    servings: 4,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1695290231381-8e75304b6281?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 50, protein: 2, carbs: 10, fat: 1 },
  },
  {
    id: 16,
    name: 'Samosa',
    category: 'vegan',
    cuisine: 'Indian',
    // Fix: Added 'as Ingredient' type assertion to fix type errors.
    ingredients: [ingredients.ALL_PURPOSE_FLOUR, ingredients.POTATOES, ingredients.GREEN_PEAS, ingredients.CUMIN_SEEDS, ingredients.CORIANDER_POWDER, { name: 'Oil for frying', category: 'Pantry Staples' } as Ingredient],
    instructions: ['Prepare a stiff dough with flour, water, and a little oil.', 'For filling: Sauté cumin seeds, add boiled mashed potatoes, peas, and spices.', 'Roll out small discs from the dough, cut in half, form cones, and stuff with filling.', 'Seal and deep fry until golden brown.'],
    prepTime: '30 min',
    cookTime: '25 min',
    servings: 6,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-04c2706196c8?q=80&w=1974&auto=format&fit=crop',
    nutrition: { calories: 260, protein: 5, carbs: 30, fat: 14 },
  },
  {
    id: 17,
    name: 'Onion Pakora',
    category: 'vegan',
    cuisine: 'Indian',
    // Fix: Added 'as Ingredient' type assertion to fix type errors.
    ingredients: [ingredients.GRAM_FLOUR, ingredients.ONION, ingredients.GREEN_CHILI, ingredients.AJWAIN, ingredients.TURMERIC, { name: 'Oil for frying', category: 'Pantry Staples' } as Ingredient],
    instructions: ['Slice onions thinly.', 'Make a thick batter with gram flour, water, sliced onions, chili, ajwain, turmeric, and salt.', 'Drop spoonfuls of the batter into hot oil and deep fry until crispy and golden.', 'Serve hot with chutney or ketchup.'],
    prepTime: '10 min',
    cookTime: '15 min',
    servings: 4,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1695290231572-1b606c1112d7?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 200, protein: 6, carbs: 20, fat: 11 },
  },
  {
    id: 18,
    name: 'Vada Pav',
    category: 'vegetarian',
    cuisine: 'Indian',
    ingredients: [ingredients.POTATOES, ingredients.GRAM_FLOUR, ingredients.PAV_BUNS, ingredients.GREEN_CHUTNEY, ingredients.GINGER_GARLIC_PASTE, ingredients.MUSTARD_SEEDS],
    instructions: ['Make potato filling with boiled mashed potatoes, mustard seeds, and ginger-garlic paste. Form into balls.', 'Make a batter with gram flour and water.', 'Dip potato balls in the batter and deep fry to make \'vada\'.', 'Slit pav buns, spread green chutney, and place a vada inside.'],
    prepTime: '20 min',
    cookTime: '20 min',
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1607373801202-9a57234b3464?q=80&w=2080&auto=format&fit=crop',
    nutrition: { calories: 310, protein: 8, carbs: 45, fat: 11 },
  },
  {
    id: 19,
    name: 'Classic Chicken Tacos',
    category: 'non-veg',
    cuisine: 'Mexican',
    ingredients: [ingredients.CHICKEN_BREAST, ingredients.TACO_SEASONING, ingredients.TORTILLAS, ingredients.LETTUCE, ingredients.TOMATO, ingredients.CHEDDAR_CHEESE, ingredients.SOUR_CREAM],
    instructions: ['Season chicken with taco seasoning and cook until done. Shred or dice.', 'Warm tortillas.', 'Assemble tacos with chicken, lettuce, tomato, cheese, and sour cream.'],
    prepTime: '10 min',
    cookTime: '15 min',
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1981&auto=format&fit=crop',
    nutrition: { calories: 480, protein: 35, carbs: 30, fat: 25 },
  },
  {
    id: 20,
    name: 'Beef Enchiladas',
    category: 'non-veg',
    cuisine: 'Mexican',
    ingredients: [ingredients.GROUND_BEEF, ingredients.ONION, ingredients.TORTILLAS, ingredients.ENCHILADA_SAUCE, ingredients.CHEDDAR_CHEESE],
    instructions: ['Preheat oven to 375°F (190°C).', 'Cook ground beef with chopped onion until browned. Drain fat.', 'Warm tortillas, fill with beef mixture, and roll them up.', 'Place in a baking dish, pour enchilada sauce over, and top with cheese.', 'Bake for 20 minutes until bubbly.'],
    prepTime: '15 min',
    cookTime: '25 min',
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1614707268735-a58913926058?q=80&w=1974&auto=format&fit=crop',
    nutrition: { calories: 550, protein: 30, carbs: 40, fat: 30 },
  },
  {
    id: 21,
    name: 'Kung Pao Chicken',
    category: 'non-veg',
    cuisine: 'Chinese',
    ingredients: [ingredients.CHICKEN_BREAST, ingredients.PEANUTS, ingredients.BELL_PEPPER, ingredients.SOY_SAUCE, ingredients.RICE_VINEGAR, ingredients.GINGER, ingredients.GARLIC, ingredients.SCALLIONS],
    instructions: ['Cut chicken into small cubes and marinate in soy sauce.', 'Heat oil in a wok, stir-fry chicken until golden.', 'Add ginger, garlic, and bell peppers. Stir-fry for a few minutes.', 'Add sauce (soy sauce, vinegar, sugar), peanuts, and scallions. Cook until sauce thickens.'],
    prepTime: '20 min',
    cookTime: '15 min',
    servings: 3,
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724489062?q=80&w=2080&auto=format&fit=crop',
    nutrition: { calories: 420, protein: 38, carbs: 20, fat: 22 },
  },
  {
    id: 22,
    name: 'Mapo Tofu',
    category: 'vegan',
    cuisine: 'Chinese',
    ingredients: [ingredients.TOFU, ingredients.CHILI_BEAN_PASTE, ingredients.SICHUAN_PEPPERCORNS, ingredients.SOY_SAUCE, ingredients.GARLIC, ingredients.GINGER, ingredients.SCALLIONS],
    instructions: ['Gently simmer tofu cubes in salted water for a few minutes, then drain.', 'Toast and grind Sichuan peppercorns.', 'Heat oil, stir-fry chili bean paste until fragrant. Add garlic and ginger.', 'Add water or vegetable broth and soy sauce. Bring to a simmer.', 'Add tofu and gently stir. Thicken with cornstarch slurry if desired. Garnish with ground peppercorns and scallions.'],
    prepTime: '10 min',
    cookTime: '15 min',
    servings: 2,
    imageUrl: 'https://images.unsplash.com/photo-1599320871635-aa7f7d3e63a1?q=80&w=1974&auto=format&fit=crop',
    nutrition: { calories: 320, protein: 20, carbs: 15, fat: 20 },
  },
  {
    id: 23,
    name: 'French Onion Soup',
    category: 'vegetarian',
    cuisine: 'French',
    ingredients: [ingredients.ONION, ingredients.VEGETABLE_BROTH, ingredients.BUTTER, ingredients.THYME, ingredients.BAGUETTE, ingredients.GRUYERE_CHEESE],
    instructions: ['Thinly slice several onions.', 'In a large pot, melt butter and cook onions slowly for 30-40 minutes until deeply caramelized.', 'Add vegetable broth and thyme, simmer for 20 minutes.', 'Ladle soup into oven-safe bowls.', 'Top each with a slice of baguette and a generous amount of Gruyère cheese.', 'Broil until cheese is melted and bubbly.'],
    prepTime: '15 min',
    cookTime: '1 hr',
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1582576302323-9a489112de2f?q=80&w=1964&auto=format&fit=crop',
    nutrition: { calories: 380, protein: 15, carbs: 35, fat: 20 },
  },
  {
    id: 24,
    name: 'Classic Ratatouille',
    category: 'vegan',
    cuisine: 'French',
    ingredients: [ingredients.EGGPLANT, ingredients.ZUCCHINI, ingredients.BELL_PEPPER, ingredients.TOMATO, ingredients.ONION, ingredients.GARLIC, ingredients.OLIVE_OIL, ingredients.HERBS_DE_PROVENCE],
    instructions: ['Chop all vegetables into similar-sized pieces.', 'Sauté onion and garlic in olive oil in a large pot.', 'Add eggplant and bell pepper, cook for 5 minutes.', 'Add zucchini and tomatoes, along with herbs de provence, salt, and pepper.', 'Cover and simmer for at least 30 minutes, or until vegetables are very tender.'],
    prepTime: '20 min',
    cookTime: '40 min',
    servings: 6,
    imageUrl: 'https://images.unsplash.com/photo-1598944983354-c87155554161?q=80&w=1974&auto=format&fit=crop',
    nutrition: { calories: 150, protein: 4, carbs: 20, fat: 7 },
  },
  // --- NEW REGIONAL INDIAN RECIPES ---
  {
    id: 25,
    name: 'Idli with Sambar',
    category: 'vegetarian',
    cuisine: 'Indian',
    ingredients: [ingredients.IDLI_RICE, ingredients.URAD_DAL, { name: 'Fenugreek seeds', category: 'Spices' } as Ingredient],
    instructions: ['Soak idli rice and urad dal separately for 4-6 hours.', 'Grind them into a smooth batter.', 'Mix the batters, add salt, and let it ferment in a warm place for 8-12 hours.', 'Pour the batter into idli molds and steam for 10-12 minutes.', 'Serve hot with Sambar and coconut chutney.'],
    prepTime: '12 hr (includes fermentation)',
    cookTime: '15 min',
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1609359419584-2191c42a5e95?q=80&w=1939&auto=format&fit=crop',
    nutrition: { calories: 200, protein: 8, carbs: 40, fat: 1 },
  },
  {
    id: 26,
    name: 'Khaman Dhokla',
    category: 'vegetarian',
    cuisine: 'Indian',
    ingredients: [ingredients.GRAM_FLOUR, ingredients.SEMOLINA, ingredients.GINGER, ingredients.GREEN_CHILI, ingredients.LEMON, ingredients.ENO, ingredients.MUSTARD_SEEDS, ingredients.CURRY_LEAVES],
    instructions: ['Make a smooth batter with gram flour, semolina, water, ginger-chili paste, and lemon juice.', 'Just before steaming, add Eno fruit salt and mix gently.', 'Pour into a greased pan and steam for 15-20 minutes.', 'For tempering, heat oil and add mustard seeds and curry leaves. Pour over the dhokla.', 'Cut into squares and serve.'],
    prepTime: '10 min',
    cookTime: '20 min',
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1625228393597-2271a33715c1?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 180, protein: 9, carbs: 25, fat: 5 },
  },
  {
    id: 27,
    name: 'Goan Fish Curry',
    category: 'non-veg',
    cuisine: 'Indian',
    ingredients: [ingredients.WHITE_FISH, ingredients.COCONUT_MILK, ingredients.ONION, ingredients.TOMATO, ingredients.TAMARIND_PASTE, ingredients.GREEN_CHILI, ingredients.GARLIC, ingredients.TURMERIC],
    instructions: ['Marinate fish with turmeric and salt.', 'Make a paste of onion, tomato, garlic, and green chili.', 'In a pan, sauté the paste until fragrant.', 'Add coconut milk, tamarind paste, and water. Bring to a simmer.', 'Gently add the fish fillets and cook until done.', 'Serve hot with steamed rice.'],
    prepTime: '15 min',
    cookTime: '20 min',
    servings: 3,
    imageUrl: 'https://images.unsplash.com/photo-1574484284004-854ae2418de0?q=80&w=1974&auto=format&fit=crop',
    nutrition: { calories: 420, protein: 35, carbs: 15, fat: 25 },
  },
  {
    id: 28,
    name: 'Rogan Josh (Lamb Curry)',
    category: 'non-veg',
    cuisine: 'Indian',
    ingredients: [ingredients.LAMB, ingredients.YOGURT, ingredients.ONION, ingredients.GINGER_GARLIC_PASTE, ingredients.KASHMIRI_CHILI_POWDER, ingredients.FENNEL_POWDER, ingredients.GINGER_POWDER, ingredients.GARAM_MASALA],
    instructions: ['Brown the lamb pieces in oil and set aside.', 'In the same oil, sauté chopped onions until golden.', 'Add ginger-garlic paste and cook for a minute.', 'Whisk yogurt with powdered spices (chili, fennel, ginger).', 'Lower the heat, add the yogurt mixture to the pot and stir continuously.', 'Return the lamb to the pot, add water, and simmer for 1-1.5 hours until the lamb is tender.', 'Finish with garam masala.'],
    prepTime: '20 min',
    cookTime: '1 hr 30 min',
    servings: 4,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1695290231422-2a6d844c3c3a?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 550, protein: 45, carbs: 10, fat: 38 },
  }
];

export const EMPTY_WEEK_PLAN: WeekPlan = [
  { day: 'Monday', breakfast: { recipes: [] }, lunch: { recipes: [] }, dinner: { recipes: [] } },
  { day: 'Tuesday', breakfast: { recipes: [] }, lunch: { recipes: [] }, dinner: { recipes: [] } },
  { day: 'Wednesday', breakfast: { recipes: [] }, lunch: { recipes: [] }, dinner: { recipes: [] } },
  { day: 'Thursday', breakfast: { recipes: [] }, lunch: { recipes: [] }, dinner: { recipes: [] } },
  { day: 'Friday', breakfast: { recipes: [] }, lunch: { recipes: [] }, dinner: { recipes: [] } },
  { day: 'Saturday', breakfast: { recipes: [] }, lunch: { recipes: [] }, dinner: { recipes: [] } },
  { day: 'Sunday', breakfast: { recipes: [] }, lunch: { recipes: [] }, dinner: { recipes: [] } },
];


export const MOCK_PANTRY_ITEMS: PantryItem[] = [
    { id: '1', name: 'Avocado', category: 'Produce' },
    { id: '2', name: 'Bread', category: 'Bakery' },
    { id: '3', name: 'Quinoa', category: 'Pantry Staples' },
    { id: '4', name: 'Eggs', category: 'Dairy' },
    { id: '5', name: 'Spaghetti', category: 'Pantry Staples' },
    { id: '6', name: 'Black Beans', category: 'Pantry Staples' },
    { id: '7', name: 'Onion', category: 'Produce' },
];