// Fix: Populating the file with mock data for the application.
import { Recipe, WeekPlan, PantryItem, Ingredient } from './types';

const ingredients = {
  BREAD: { name: '2 slices of whole wheat bread', category: 'Bakery' } as Ingredient,
  AVOCADO: { name: '1 avocado', category: 'Produce' } as Ingredient,
  EGGS: { name: '2 large eggs', category: 'Dairy' } as Ingredient,
  RED_PEPPER_FLAKES: { name: '1/4 tsp red pepper flakes', category: 'Spices' } as Ingredient,
  SALT_PEPPER: { name: 'Salt and pepper', category: 'Spices' } as Ingredient,
  CHICKEN_BREAST: { name: '1 grilled chicken breast, sliced', category: 'Protein' } as Ingredient,
  MIXED_GREENS: { name: '4 cups mixed greens', category: 'Produce' } as Ingredient,
  CHERRY_TOMATOES: { name: '1/2 cup cherry tomatoes, halved', category: 'Produce' } as Ingredient,
  CUCUMBER: { name: '1/4 cup cucumber, sliced', category: 'Produce' } as Ingredient,
  VINAIGRETTE: { name: '2 tbsp vinaigrette', category: 'Pantry Staples' } as Ingredient,
  GROUND_BEEF: { name: '1 lb ground beef', category: 'Protein' } as Ingredient,
  ONION: { name: '1 onion, chopped', category: 'Produce' } as Ingredient,
  GARLIC: { name: '2 cloves garlic, minced', category: 'Produce' } as Ingredient,
  CRUSHED_TOMATOES: { name: '1 (28 ounce) can crushed tomatoes', category: 'Pantry Staples' } as Ingredient,
  TOMATO_PASTE: { name: '1 (6 ounce) can tomato paste', category: 'Pantry Staples' } as Ingredient,
  OREGANO: { name: '1 tsp dried oregano', category: 'Spices' } as Ingredient,
  SPAGHETTI: { name: '1 pound spaghetti', category: 'Pantry Staples' } as Ingredient,
  QUINOA: { name: '1 cup cooked quinoa', category: 'Pantry Staples' } as Ingredient,
  BLACK_BEANS: { name: '1/2 cup black beans, rinsed', category: 'Pantry Staples' } as Ingredient,
  CORN: { name: '1/2 cup corn', category: 'Produce' } as Ingredient,
  BELL_PEPPER: { name: '1/2 bell pepper, chopped', category: 'Produce' } as Ingredient,
  SALSA: { name: '1/4 cup salsa', category: 'Pantry Staples' } as Ingredient,
  GREEK_YOGURT: { name: '1 cup Greek yogurt', category: 'Dairy' } as Ingredient,
  MIXED_BERRIES: { name: '1/2 cup mixed berries', category: 'Produce' } as Ingredient,
  GRANOLA: { name: '1/4 cup granola', category: 'Pantry Staples' } as Ingredient,
  HONEY: { name: '1 tbsp honey', category: 'Pantry Staples' } as Ingredient,
  SALMON_FILLET: { name: '1 salmon fillet (6 oz)', category: 'Protein' } as Ingredient,
  ASPARAGUS: { name: '1 bunch asparagus, trimmed', category: 'Produce' } as Ingredient,
  OLIVE_OIL: { name: '1 tbsp olive oil', category: 'Pantry Staples' } as Ingredient,
  LEMON: { name: '1 lemon, sliced', category: 'Produce' } as Ingredient,
  // Indian Ingredients
  POHA: { name: '1.5 cups thick poha (flattened rice)', category: 'Pantry Staples' } as Ingredient,
  TURMERIC: { name: '1/4 tsp turmeric powder', category: 'Spices' } as Ingredient,
  MUSTARD_SEEDS: { name: '1 tsp mustard seeds', category: 'Spices' } as Ingredient,
  CURRY_LEAVES: { name: '8-10 curry leaves', category: 'Produce' } as Ingredient,
  GREEN_CHILI: { name: '1-2 green chilies, chopped', category: 'Produce' } as Ingredient,
  CORIANDER_LEAVES: { name: '2 tbsp chopped coriander leaves', category: 'Produce' } as Ingredient,
  CHICKPEAS: { name: '1 cup dried chickpeas, soaked overnight', category: 'Pantry Staples' } as Ingredient,
  ALL_PURPOSE_FLOUR: { name: '2 cups all-purpose flour', category: 'Pantry Staples' } as Ingredient,
  YOGURT: { name: '1/4 cup yogurt', category: 'Dairy' } as Ingredient,
  PANEER: { name: '250g paneer, cubed', category: 'Dairy' } as Ingredient,
  GINGER_GARLIC_PASTE: { name: '1 tbsp ginger-garlic paste', category: 'Produce' } as Ingredient,
  TOMATO_PUREE: { name: '1 cup tomato puree', category: 'Pantry Staples' } as Ingredient,
  TOMATO: { name: '1 medium tomato, chopped', category: 'Produce' } as Ingredient,
  CASHEWS: { name: '10-12 cashews', category: 'Pantry Staples' } as Ingredient,
  GARAM_MASALA: { name: '1 tsp garam masala', category: 'Spices' } as Ingredient,
  CREAM: { name: '1/4 cup heavy cream', category: 'Dairy' } as Ingredient,
  CHICKEN: { name: '500g chicken, bone-in', category: 'Protein' } as Ingredient,
  BASMATI_RICE: { name: '2 cups basmati rice, soaked', category: 'Pantry Staples' } as Ingredient,
  BIRYANI_MASALA: { name: '2 tbsp biryani masala', category: 'Spices' } as Ingredient,
  MINT_LEAVES: { name: '1/4 cup mint leaves', category: 'Produce' } as Ingredient,
  DOSA_RICE: { name: '1.5 cups dosa rice', category: 'Pantry Staples' } as Ingredient,
  URAD_DAL: { name: '1/2 cup urad dal', category: 'Pantry Staples' } as Ingredient,
  POTATOES: { name: '2 medium potatoes, boiled and mashed', category: 'Produce' } as Ingredient,
  SAMBAR_POWDER: { name: '2 tsp sambar powder', category: 'Spices' } as Ingredient,
  TOOR_DAL: { name: '1 cup toor dal (split pigeon peas)', category: 'Pantry Staples' } as Ingredient,
  CUMIN_SEEDS: { name: '1 tsp cumin seeds', category: 'Spices' } as Ingredient,
  DRIED_RED_CHILI: { name: '2 dried red chilies', category: 'Spices' } as Ingredient,
  // New South Indian & Snack Ingredients
  TAMARIND_PULP: { name: '1 tbsp tamarind pulp', category: 'Pantry Staples' } as Ingredient,
  MIXED_VEGETABLES: { name: '1 cup mixed vegetables (carrots, beans, drumstick)', category: 'Produce' } as Ingredient,
  GRATED_COCONUT: { name: '1/2 cup grated coconut', category: 'Produce' } as Ingredient,
  RASAM_POWDER: { name: '2 tsp rasam powder', category: 'Spices' } as Ingredient,
  BLACK_PEPPER: { name: '1 tsp black pepper', category: 'Spices' } as Ingredient,
  GREEN_PEAS: { name: '1/2 cup green peas', category: 'Produce' } as Ingredient,
  CORIANDER_POWDER: { name: '1 tsp coriander powder', category: 'Spices' } as Ingredient,
  GRAM_FLOUR: { name: '1 cup gram flour (besan)', category: 'Pantry Staples' } as Ingredient,
  AJWAIN: { name: '1/2 tsp ajwain (carom seeds)', category: 'Spices' } as Ingredient,
  PAV_BUNS: { name: '4 pav (bread buns)', category: 'Bakery' } as Ingredient,
  GREEN_CHUTNEY: { name: '2 tbsp green chutney', category: 'Pantry Staples' } as Ingredient,
};

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 1,
    name: 'Avocado Toast with Egg',
    category: 'vegetarian',
    ingredients: [ingredients.BREAD, ingredients.AVOCADO, ingredients.EGGS, ingredients.RED_PEPPER_FLAKES, ingredients.SALT_PEPPER],
    instructions: ['Toast bread slices.', 'Mash avocado and spread on toast.', 'Cook eggs as desired (fried or poached).', 'Place egg on top of avocado toast and season.'],
    prepTime: '5 min',
    cookTime: '5 min',
    servings: 1,
    imageUrl: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?q=80&w=1910&auto=format&fit=crop',
    nutrition: { calories: 350, protein: 15, carbs: 30, fat: 20 },
  },
  {
    id: 2,
    name: 'Grilled Chicken Salad',
    category: 'non-veg',
    ingredients: [ingredients.CHICKEN_BREAST, ingredients.MIXED_GREENS, ingredients.CHERRY_TOMATOES, ingredients.CUCUMBER, ingredients.VINAIGRETTE],
    instructions: ['In a large bowl, combine mixed greens, tomatoes, and cucumber.', 'Top with sliced grilled chicken.', 'Drizzle with vinaigrette and toss to combine.'],
    prepTime: '10 min',
    cookTime: '0 min',
    servings: 1,
    imageUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?q=80&w=1974&auto=format&fit=crop',
    nutrition: { calories: 400, protein: 40, carbs: 10, fat: 22 },
  },
  {
    id: 3,
    name: 'Spaghetti Bolognese',
    category: 'non-veg',
    ingredients: [ingredients.GROUND_BEEF, ingredients.ONION, ingredients.GARLIC, ingredients.CRUSHED_TOMATOES, ingredients.TOMATO_PASTE, ingredients.OREGANO, ingredients.SPAGHETTI],
    instructions: ['Cook beef, onion, and garlic in a large pot. Drain fat.', 'Stir in tomatoes, tomato paste, and oregano. Simmer for 1 hour.', 'Cook spaghetti according to package directions.', 'Serve sauce over spaghetti.'],
    prepTime: '15 min',
    cookTime: '1 hr 15 min',
    servings: 6,
    imageUrl: 'https://images.unsplash.com/photo-1589227365533-5f6e6ab5ef75?q=80&w=1974&auto=format&fit=crop',
    nutrition: { calories: 650, protein: 30, carbs: 80, fat: 25 },
  },
  {
    id: 4,
    name: 'Quinoa Bowl with Veggies',
    category: 'vegan',
    ingredients: [ingredients.QUINOA, ingredients.BLACK_BEANS, ingredients.CORN, ingredients.BELL_PEPPER, ingredients.SALSA],
    instructions: ['Combine quinoa, black beans, corn, and bell pepper in a bowl.', 'Top with salsa and mix well.'],
    prepTime: '10 min',
    cookTime: '0 min',
    servings: 1,
    imageUrl: 'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?q=80&w=1964&auto=format&fit=crop',
    nutrition: { calories: 380, protein: 15, carbs: 70, fat: 5 },
  },
   {
    id: 5,
    name: 'Greek Yogurt Parfait',
    category: 'vegetarian',
    ingredients: [ingredients.GREEK_YOGURT, ingredients.MIXED_BERRIES, ingredients.GRANOLA, ingredients.HONEY],
    instructions: ['Layer Greek yogurt, berries, and granola in a glass.', 'Drizzle with honey before serving.'],
    prepTime: '5 min',
    cookTime: '0 min',
    servings: 1,
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17025?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 300, protein: 20, carbs: 40, fat: 8 },
  },
  {
    id: 6,
    name: 'Salmon with Asparagus',
    category: 'non-veg',
    ingredients: [ingredients.SALMON_FILLET, ingredients.ASPARAGUS, ingredients.OLIVE_OIL, ingredients.LEMON, ingredients.SALT_PEPPER],
    instructions: ['Preheat oven to 400°F (200°C).', 'Toss asparagus with olive oil, salt, and pepper on a baking sheet.', 'Place salmon on top, season, and top with lemon slices.', 'Bake for 12-15 minutes.'],
    prepTime: '5 min',
    cookTime: '15 min',
    servings: 1,
    imageUrl: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 450, protein: 45, carbs: 10, fat: 28 },
  },
  // --- Indian Recipes Start Here ---
  {
    id: 7,
    name: 'Poha',
    category: 'vegetarian',
    ingredients: [ingredients.POHA, ingredients.ONION, ingredients.OLIVE_OIL, ingredients.MUSTARD_SEEDS, ingredients.CURRY_LEAVES, ingredients.TURMERIC, ingredients.GREEN_CHILI, ingredients.LEMON, ingredients.CORIANDER_LEAVES],
    instructions: ['Rinse poha in a strainer and let it soften.', 'Heat oil, add mustard seeds, curry leaves, and green chili.', 'Sauté chopped onions until translucent.', 'Add turmeric, then the softened poha and salt. Mix well.', 'Garnish with lemon juice and coriander.'],
    prepTime: '10 min',
    cookTime: '10 min',
    servings: 2,
    imageUrl: 'https://images.unsplash.com/photo-1609503222839-8197c36a053c?q=80&w=2071&auto=format&fit=crop',
    nutrition: { calories: 250, protein: 5, carbs: 50, fat: 4 },
  },
  {
    id: 8,
    name: 'Chole Bhature',
    category: 'vegetarian',
    ingredients: [ingredients.CHICKPEAS, ingredients.ONION, ingredients.TOMATO_PUREE, ingredients.GINGER_GARLIC_PASTE, ingredients.GARAM_MASALA, ingredients.ALL_PURPOSE_FLOUR, ingredients.YOGURT, ingredients.OLIVE_OIL],
    instructions: ['For Chole: Pressure cook soaked chickpeas. Sauté onions, ginger-garlic paste, and tomato puree. Add spices and cooked chickpeas. Simmer.', 'For Bhature: Make a dough with flour, yogurt, and a little oil. Let it rest. Roll out and deep fry until puffed.'],
    prepTime: '20 min',
    cookTime: '45 min',
    servings: 4,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1663852297241-b7781b41d2a4?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 550, protein: 15, carbs: 75, fat: 20 },
  },
  {
    id: 9,
    name: 'Paneer Butter Masala',
    category: 'vegetarian',
    ingredients: [ingredients.PANEER, ingredients.TOMATO_PUREE, ingredients.ONION, ingredients.CASHEWS, ingredients.GINGER_GARLIC_PASTE, ingredients.GARAM_MASALA, ingredients.CREAM, { name: '1 tbsp butter', category: 'Dairy' }],
    instructions: ['Sauté paneer cubes lightly and set aside.', 'Make a gravy by blending sautéed onions, tomatoes, cashews, and ginger-garlic paste.', 'Cook the gravy with butter and spices.', 'Add paneer and cream. Simmer for a few minutes.'],
    prepTime: '15 min',
    cookTime: '25 min',
    servings: 3,
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 450, protein: 20, carbs: 15, fat: 35 },
  },
  {
    id: 10,
    name: 'Chicken Biryani',
    category: 'non-veg',
    ingredients: [ingredients.CHICKEN, ingredients.BASMATI_RICE, ingredients.YOGURT, ingredients.ONION, ingredients.GINGER_GARLIC_PASTE, ingredients.BIRYANI_MASALA, ingredients.MINT_LEAVES, { name: 'A pinch of saffron', category: 'Spices' }],
    instructions: ['Marinate chicken with yogurt and spices.', 'Fry onions until golden brown.', 'Par-cook the soaked basmati rice.', 'Layer the rice and chicken in a heavy-bottomed pot.', 'Top with fried onions, mint, and saffron milk. Cook on low heat (dum).'],
    prepTime: '30 min',
    cookTime: '1 hr',
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8da7?q=80&w=1974&auto=format&fit=crop',
    nutrition: { calories: 600, protein: 35, carbs: 60, fat: 25 },
  },
  {
    id: 11,
    name: 'Masala Dosa',
    category: 'vegan',
    ingredients: [ingredients.DOSA_RICE, ingredients.URAD_DAL, ingredients.POTATOES, ingredients.ONION, ingredients.TURMERIC, ingredients.MUSTARD_SEEDS, ingredients.GREEN_CHILI, ingredients.OLIVE_OIL],
    instructions: ['Soak rice and dal, then grind to a batter and ferment overnight.', 'For masala: Sauté mustard seeds, onions, and chilies. Add turmeric and mashed potatoes.', 'Spread the batter thinly on a hot pan to make a dosa. Add filling and fold.'],
    prepTime: '12 hr (includes fermentation)',
    cookTime: '20 min',
    servings: 5,
    imageUrl: 'https://images.unsplash.com/photo-1643216343038-92f784bf1d43?q=80&w=1974&auto=format&fit=crop',
    nutrition: { calories: 300, protein: 8, carbs: 55, fat: 5 },
  },
  {
    id: 12,
    name: 'Dal Tadka',
    category: 'vegan',
    ingredients: [ingredients.TOOR_DAL, ingredients.ONION, ingredients.TOMATO, ingredients.GINGER_GARLIC_PASTE, ingredients.TURMERIC, ingredients.CUMIN_SEEDS, ingredients.DRIED_RED_CHILI, ingredients.CORIANDER_LEAVES, ingredients.OLIVE_OIL],
    instructions: ['Pressure cook the toor dal with turmeric and salt.', 'For tadka (tempering): Heat oil/ghee, add cumin seeds, dried red chili, and asafoetida.', 'Sauté onions, ginger-garlic paste, and tomatoes.', 'Pour the tadka over the cooked dal. Garnish with coriander.'],
    prepTime: '10 min',
    cookTime: '20 min',
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a0586276d8?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 280, protein: 15, carbs: 40, fat: 6 },
  },
  // --- New South Indian & Snack Recipes ---
  {
    id: 13,
    name: 'Sambar',
    category: 'vegetarian',
    ingredients: [ingredients.TOOR_DAL, ingredients.TAMARIND_PULP, ingredients.SAMBAR_POWDER, ingredients.MIXED_VEGETABLES, ingredients.MUSTARD_SEEDS, ingredients.CURRY_LEAVES],
    instructions: ['Pressure cook toor dal until soft.', 'Cook vegetables in water with sambar powder and salt.', 'Add tamarind pulp and cooked dal to the vegetables and bring to a boil.', 'Prepare tempering with mustard seeds and curry leaves in oil and add to the sambar.'],
    prepTime: '15 min',
    cookTime: '30 min',
    servings: 4,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1695289949132-888915523a85?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 220, protein: 12, carbs: 35, fat: 4 },
  },
  {
    id: 14,
    name: 'Avial',
    category: 'vegetarian',
    ingredients: [ingredients.MIXED_VEGETABLES, ingredients.GRATED_COCONUT, ingredients.YOGURT, ingredients.GREEN_CHILI, ingredients.CURRY_LEAVES, { name: '1 tsp coconut oil', category: 'Pantry Staples' }],
    instructions: ['Cook mixed vegetables until tender.', 'Grind coconut and green chilies to a fine paste.', 'Add the coconut paste to the cooked vegetables and cook for a few minutes.', 'Whisk yogurt and add it to the curry. Do not boil after adding yogurt.', 'Top with curry leaves and coconut oil.'],
    prepTime: '20 min',
    cookTime: '25 min',
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1644284240952-32a8a1b621a2?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 180, protein: 5, carbs: 15, fat: 12 },
  },
  {
    id: 15,
    name: 'Rasam',
    category: 'vegan',
    ingredients: [ingredients.TAMARIND_PULP, ingredients.TOMATO, ingredients.RASAM_POWDER, ingredients.BLACK_PEPPER, ingredients.MUSTARD_SEEDS, ingredients.GARLIC],
    instructions: ['Dilute tamarind pulp in water. Add chopped tomatoes, rasam powder, and salt. Boil.', 'Crush garlic and black pepper.', 'Prepare tempering with mustard seeds in oil, add crushed garlic and pepper.', 'Add tempering to the boiling rasam. Garnish with coriander.'],
    prepTime: '5 min',
    cookTime: '15 min',
    servings: 4,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1695290231381-8e75304b6281?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 50, protein: 2, carbs: 10, fat: 1 },
  },
  {
    id: 16,
    name: 'Samosa',
    category: 'vegan',
    ingredients: [ingredients.ALL_PURPOSE_FLOUR, ingredients.POTATOES, ingredients.GREEN_PEAS, ingredients.CUMIN_SEEDS, ingredients.CORIANDER_POWDER, { name: 'Oil for frying', category: 'Pantry Staples' }],
    instructions: ['Prepare a stiff dough with flour, water, and a little oil.', 'For filling: Sauté cumin seeds, add boiled mashed potatoes, peas, and spices.', 'Roll out small discs from the dough, cut in half, form cones, and stuff with filling.', 'Seal and deep fry until golden brown.'],
    prepTime: '30 min',
    cookTime: '25 min',
    servings: 6,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-04c2706196c8?q=80&w=1974&auto=format&fit=crop',
    nutrition: { calories: 260, protein: 5, carbs: 30, fat: 14 },
  },
  {
    id: 17,
    name: 'Onion Pakora',
    category: 'vegan',
    ingredients: [ingredients.GRAM_FLOUR, ingredients.ONION, ingredients.GREEN_CHILI, ingredients.AJWAIN, ingredients.TURMERIC, { name: 'Oil for frying', category: 'Pantry Staples' }],
    instructions: ['Slice onions thinly.', 'Make a thick batter with gram flour, water, sliced onions, chili, ajwain, turmeric, and salt.', 'Drop spoonfuls of the batter into hot oil and deep fry until crispy and golden.', 'Serve hot with chutney or ketchup.'],
    prepTime: '10 min',
    cookTime: '15 min',
    servings: 4,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1695290231572-1b606c1112d7?q=80&w=2070&auto=format&fit=crop',
    nutrition: { calories: 200, protein: 6, carbs: 20, fat: 11 },
  },
  {
    id: 18,
    name: 'Vada Pav',
    category: 'vegetarian',
    ingredients: [ingredients.POTATOES, ingredients.GRAM_FLOUR, ingredients.PAV_BUNS, ingredients.GREEN_CHUTNEY, ingredients.GINGER_GARLIC_PASTE, ingredients.MUSTARD_SEEDS],
    instructions: ['Make potato filling with boiled mashed potatoes, mustard seeds, and ginger-garlic paste. Form into balls.', 'Make a batter with gram flour and water.', 'Dip potato balls in the batter and deep fry to make \'vada\'.', 'Slit pav buns, spread green chutney, and place a vada inside.'],
    prepTime: '20 min',
    cookTime: '20 min',
    servings: 4,
    imageUrl: 'https://images.unsplash.com/photo-1607373801202-9a57234b3464?q=80&w=2080&auto=format&fit=crop',
    nutrition: { calories: 310, protein: 8, carbs: 45, fat: 11 },
  }
];

export const EMPTY_WEEK_PLAN: WeekPlan = [
  { day: 'Monday', breakfast: { recipe: null }, lunch: { recipe: null }, dinner: { recipe: null } },
  { day: 'Tuesday', breakfast: { recipe: null }, lunch: { recipe: null }, dinner: { recipe: null } },
  { day: 'Wednesday', breakfast: { recipe: null }, lunch: { recipe: null }, dinner: { recipe: null } },
  { day: 'Thursday', breakfast: { recipe: null }, lunch: { recipe: null }, dinner: { recipe: null } },
  { day: 'Friday', breakfast: { recipe: null }, lunch: { recipe: null }, dinner: { recipe: null } },
  { day: 'Saturday', breakfast: { recipe: null }, lunch: { recipe: null }, dinner: { recipe: null } },
  { day: 'Sunday', breakfast: { recipe: null }, lunch: { recipe: null }, dinner: { recipe: null } },
];


export const MOCK_PANTRY_ITEMS: PantryItem[] = [
    { id: '1', name: 'Avocado', category: 'Produce' },
    { id: '2', name: 'Bread', category: 'Bakery' },
    { id: '3', name: 'Quinoa', category: 'Pantry Staples' },
    { id: '4', name: 'Eggs', category: 'Dairy' },
    { id: '5', name: 'Spaghetti', category: 'Pantry Staples' },
    { id: '6', name: 'Black Beans', category: 'Pantry Staples' },
    { id: '7', name: 'Onion', category: 'Produce' },
];